library calc_manager

interface Programmer {
    commands: (value: stream int) -> stream int,
    commandss: static (value: stream int) -> stream int,
}

enum Command {
    Hex,
    Dec,
    Oct,
    Bin,
    Qword,
    Dword,
    Word,
    Byte,
}

struct Point {
    x: int,
    y: int,
}

struct Size {
    width: float,
    height: float,
}